export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';
// get clients by IDs
export const GET_CLIENTS_BY_ID = 'GET_CLIENTS_BY_ID';
export const GET_CLIENTS_BY_ID_SUCCESS = 'GET_CLIENTS_BY_ID_SUCCESS';
export const GET_CLIENTS_BY_ID_FAILURE = 'GET_CLIENTS_BY_ID_FAILURE';
