export const FETCH_SP_REQUEST = "FETCH_SP_REQUEST";
export const FETCH_SP_SUCCESS = "FETCH_SP_SUCCESS";
export const FETCH_SP_FAILURE = "FETCH_SP_FAILURE";

export const FETCH_SP_BY_ID_REQUEST = "FETCH_SP_BY_ID_REQUEST";
export const FETCH_SP_BY_ID_SUCCESS = "FETCH_SP_BY_ID_SUCCESS";
export const FETCH_SP_BY_ID_FAILURE = "FETCH_SP_BY_ID_FAILURE";
