export const FETCH_SP_REQUEST = "FETCH_SP_REQUEST";
export const FETCH_SP_SUCCESS = "FETCH_SP_SUCCESS";
export const FETCH_SP_FAILURE = "FETCH_SP_FAILURE";

export const FETCH_SP_BY_ID_REQUEST = "FETCH_SP_BY_ID_REQUEST";
export const FETCH_SP_BY_ID_SUCCESS = "FETCH_SP_BY_ID_SUCCESS";
export const FETCH_SP_BY_ID_FAILURE = "FETCH_SP_BY_ID_FAILURE";


//SAVE MEETING
export const SAVE_MEETING = "SAVE_MEETING";
export const SAVE_MEETING_SUCCESS = "SAVE_MEETING_SUCCESS";
export const SAVE_MEETING_FAILURE = "SAVE_MEETING_FAILURE";

//FETCH MEETINGS
export const FETCH_MEETINGS_BY_ID_REQUEST = "FETCH_MEETINGS_BY_ID_REQUEST"
export const FETCH_MEETINGS_BY_ID_SUCCESS = "FETCH_MEETINGS_BY_ID_SUCCESS"
export const FETCH_MEETINGS_BY_ID_FAILURE = "FETCH_MEETINGS_BY_ID_FAILURE"

